proxy-groups:

  - name: "PROXY"
    type: load-balance
    proxies:
      - hk
      - jp
    url: 'http://www.gstatic.com/generate_204'
    interval: 10000

  - name: "jp"
    type: load-balance
    proxies:
      - jp1
      - jp2
      - jp3
      - jp4
    url: 'http://www.gstatic.com/generate_204'
    interval: 1000
    strategy: round-robin

  - name: "hk"
    type: load-balance
    proxies:
      - hk1
      - hk2
    url: 'http://www.gstatic.com/generate_204'
    interval: 1000
    strategy: round-robin   

proxies:

  - name: hk1
    server: webservice.eastasia.cloudapp.azure.com
    port: 443
    type: trojan
    password: "1234"
    udp: true    
    network: grpc
    grpc-opts:
      grpc-service-name: "Message"

  - name: hk2
    server: webservice.eastasia.cloudapp.azure.com
    port: 80
    type: trojan
    password: "1234"
    udp: true

  - name: jp1
    server: hello.orangeflower-02e57fda.japaneast.azurecontainerapps.io
    port: 443
    type: trojan
    password: "1234"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "Message"

  - name: jp2
    server: hello2.orangeflower-02e57fda.japaneast.azurecontainerapps.io
    port: 443
    type: trojan
    password: "1234"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "Message"

  - name: jp3
    server: hello3.orangeflower-02e57fda.japaneast.azurecontainerapps.io
    port: 443
    type: trojan
    password: "1234"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "Message"

  - name: jp4
    server: hello4.orangeflower-02e57fda.japaneast.azurecontainerapps.io
    port: 443
    type: trojan
    password: "1234"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "Message"

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - DOMAIN-KEYWORD,azure,DIRECT
  - DOMAIN-KEYWORD,microsoft,DIRECT
  - DOMAIN-KEYWORD,bing,DIRECT
  - DOMAIN-KEYWORD,msedge,DIRECT
  - DOMAIN-KEYWORD,windows,DIRECT
  - DOMAIN-KEYWORD,fastcloud,DIRECT  

  - DOMAIN-SUFFIX,azurecontainerapps.io,DIRECT

  - RULE-SET,applications,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY

dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
  fallback:
    - 1.1.1.1
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
    - 127.0.0.1